services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-wordpress
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: wppassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: .
    container_name: wordpress-php
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./clickstream-wp:/var/www/html/wp-content/plugins/clickstream-wp
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
    depends_on:
      - mariadb

volumes:
  mariadb_data: